architecture: replication
auth:
  enabled: false
# TODO... n8n doesn't support sentinel
# sentinel:
#   enabled: true
#   masterSet: "mymaster"
#   image:
#     repository: bitnamilegacy/redis-sentinel
#     tag: 7.2.4-debian-12-r9
master:
  persistence:
    enabled: true
    size: 2Gi # [CONFIG] size accordingly
replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 2Gi # [CONFIG] size accordingly
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
image:
  repository: bitnamilegacy/redis
  tag: 7.2.4-debian-12-r9
global:
  security:
    allowInsecureImages: true
    # TODO: We should look for a supported redis alternative.