
# TODO: add image block
image:
  repository: bitovi/n8n-community-nodes
  pullPolicy: Always
  tag: "1.122.4"

main:
  # n8n Configuration
  config:
    executions:
      mode: queue
      timeout: 300
      maxTimeout: 3600
    
    # Database configuration
    db:
      type: postgresdb
      postgresdb:
        host: cnpg-cluster-rw.cnpg.svc
        port: 5432
        database: n8n
        user: n8n

  extraEnv:
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-db-password
          key: password
    GENERIC_TIMEZONE:
      value: "America/Chicago"

    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
      value: "true"
    N8N_PORT:
      value: "5678"

    N8N_RUNNERS_ENABLED:
      value: "true"
    N8N_RUNNERS_MODE:
      value: "internal"
    N8N_RUNNERS_AUTH_TOKEN:
      value: "temp_for_testing"
    N8N_RUNNERS_BROKER_LISTEN_ADDRESS:
      value: "0.0.0.0"
    N8N_EXECUTIONS_PROCESS:
      value: "false"


    # try NOT setting these but setting it on the workers
    # TODO: i'm pretty sure only one of these is respected...
    # N8N_EXECUTIONS_MODE:
    #   value: "queue"
    # EXECUTIONS_MODE:
    #   value: "queue"

    N8N_LOG_LEVEL:
      value: "debug"

    N8N_HOST:
      value: "localhost"
    N8N_EDITOR_BASE_URL:
      value: "https://n8n-test.mukunda.com"
    VUE_APP_URL_BASE_API:
      value: "https://n8n-test.mukunda.com/"

    WEBHOOK_URL:
      value: "https://n8n-test.mukunda.com"

    N8N_METRICS:
      value: "true"

    N8N_LISTEN_ADDRESS:
      value: "0.0.0.0"
    N8N_SECURE_COOKIE:
      value: "false"

    NODE_FUNCTION_ALLOW_EXTERNAL:
      value: "date-fns"

    QUEUE_BULL_REDIS_TLS:
      value: "false"
    QUEUE_BULL_REDIS_HOST:
      value: "redis-master.redis.svc"
    QUEUE_BULL_REDIS_PORT:
      value: "6379"

  # Persistence
  persistence:
    enabled: true
    type: dynamic
    size: 1Gi

worker:
  # Service configuration
  service:
    type: ClusterIP
    port: 5678
  # Desired worker pods.
  replicaCount: 1

  extraEnv:
    DB_POSTGRESDB_PASSWORD:
      valueFrom:
        secretKeyRef:
          name: n8n-db-password
          key: password
    GENERIC_TIMEZONE:
      value: "America/Chicago"
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS:
      value: "true"
    N8N_PORT:
      value: "5678"
    N8N_RUNNERS_ENABLED:
      value: "true"
    N8N_RUNNERS_MODE:
      value: "internal"
    N8N_RUNNERS_AUTH_TOKEN:
      value: "temp_for_testing"
    N8N_RUNNERS_BROKER_LISTEN_ADDRESS:
      value: "0.0.0.0"
    N8N_EXECUTIONS_PROCESS:
      value: "false"
    N8N_LOG_LEVEL:
      value: "debug"
    N8N_HOST:
      value: "localhost"
    N8N_EDITOR_BASE_URL:
      value: "https://n8n-test.mukunda.com"
    VUE_APP_URL_BASE_API:
      value: "https://n8n-test.mukunda.com/"
    WEBHOOK_URL:
      value: "https://n8n-test.mukunda.com"
    N8N_METRICS:
      value: "true"
    N8N_LISTEN_ADDRESS:
      value: "0.0.0.0"
    N8N_SECURE_COOKIE:
      value: "false"
    NODE_FUNCTION_ALLOW_EXTERNAL:
      value: "date-fns"
    QUEUE_BULL_REDIS_TLS:
      value: "false"
    QUEUE_BULL_REDIS_HOST:
      value: "redis-master.redis.svc"
    QUEUE_BULL_REDIS_PORT:
      value: "6379"

# Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: n8n.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: n8n-tls
    #   hosts:
    #     - n8n.example.com

# Resources (TODO)
# resources:
#   requests:
#     memory: "512Mi"
#     cpu: "500m"
#   limits:
#     memory: "1Gi"
#     cpu: "1000m"
