
main:
  # n8n Configuration
  config:
    executions:
      mode: queue
      timeout: 300
      maxTimeout: 3600
    
    # Database configuration (optional - uses SQLite by default)
    database:
      type: postgresdb
      postgresdb:
        host: cluster-rw.cpng.svc
        port: 5432
        database: n8n
        user: n8n

  # Persistence
  persistence:
    enabled: true
    type: dynamic
    size: 1Gi

worker:
  # Service configuration
  service:
    type: ClusterIP
    port: 5678
  # Desired worker pods.
  replicaCount: 1

# Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: n8n.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
    # - secretName: n8n-tls
    #   hosts:
    #     - n8n.example.com

# Resources (TODO)
# resources:
#   requests:
#     memory: "512Mi"
#     cpu: "500m"
#   limits:
#     memory: "1Gi"
#     cpu: "1000m"

# Additional environment variables
# extraEnv:
#   - name: N8N_BASIC_AUTH_ACTIVE
#     value: "true"
#   - name: N8N_BASIC_AUTH_USER
#     value: "admin"
#   - name: N8N_BASIC_AUTH_PASSWORD
#     value: "changeme"
#   - name: WEBHOOK_URL
#     value: "https://n8n.example.com/"

extraEnv:
  DB_POSTGRESDB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: n8n-db-password
        key: password
