# cluster:
#   roles:
#     - name: n8n
#       ensure: present
#       passwordSecret:
#         name: n8n-db-password
#         key: password
      
# databases:
#   - name: n8n
#     ensure: present
#     owner: n8n
