apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: test-node-pool
spec:
  # Static node count for testing.
  replicas: 3

  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default

      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["t"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: In
          values: ["3"]
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["t3a"]
        - key: "eks.amazonaws.com/instance-size"
          operator: In
          values: ["medium"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b", "us-east-1c"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]

  # Generic limit block for blocking excessive resource usage.
  # Not used with the static replica count above.
  #limits:
    #cpu: "100"
    #memory: 100Gi

