ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`n8n-traefik.bitovi-ai.com`)
    entryPoints:
      - web
service:
  enabled: true
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      port: 80
      protocol: HTTP
      namespacePolicy:
        from: All
    websecure:
      port: 443
      protocol: HTTPS
      namespacePolicy:
        from: All
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: n8n-test-bitovi-ai-com-tls
          group: ""

ports:
  # Defines the HTTP entry point named 'web'
  web:
    port: 80
    nodePort: 30000
    # Instructs this entry point to redirect all traffic to the 'websecure' entry point
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: false
  # Defines the HTTPS entry point named 'websecure'
  websecure:
    port: 443
    nodePort: 30001