ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`n8n-traefik.bitovi-ai.com`)
    entryPoints:
      - web
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
