apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox
  namespace: argocd
  labels:
    managed-by: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mukunda-/argo-n8n-d1
    targetRevision: HEAD
    path: apps/busybox/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: busybox
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true